# Generated by Django 4.1.4 on 2023-04-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0)),
                ('species', models.IntegerField(choices=[(0, 'Human'), (1, 'Dragonborn'), (2, 'Dwarf'), (3, 'Elf'), (4, 'Gnome'), (5, 'Goliath'), (6, 'HalfOrc'), (7, 'Halfling'), (8, 'Vampire')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Sloop'), (2, 'Schooner'), (2, 'Brig'), (3, 'Galleon'), (4, 'Man-O-War')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ships.character')),
                ('role', models.CharField(default='Crew', max_length=30)),
                ('co', models.CharField(max_length=30)),
                ('important', models.BooleanField(default=False)),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ships.ship')),
            ],
            bases=('ships.character',),
        ),
    ]
