# Generated by Django 4.0.3 on 2022-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_continent_location_nation_organisation_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
