# Generated by Django 4.0.3 on 2022-03-10 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.nation'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.continent'),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.location'),
        ),
    ]
