# Generated by Django 4.0.3 on 2022-03-11 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_captain', to='blog.person')),
                ('crew', models.ManyToManyField(blank=True, to='blog.person')),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.location')),
            ],
        ),
    ]
