# Generated by Django 4.0.3 on 2022-03-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_location_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Type',
            new_name='type',
        ),
    ]
